// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/get-stock-price.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^4.4.3";
var get_stock_price_default = defineTool({
  name: "get_stock_price",
  title: "Get stock price",
  description: "Get the latest price, absolute change, and percent change for a PSX (Pakistan Stock Exchange) or US stock ticker.",
  inputSchema: {
    ticker: z.string().trim().min(1).describe('Ticker symbol, e.g. "OGDC" for PSX or "AAPL" for US.'),
    market: z.enum(["PSX", "US"]).default("PSX").describe("Which market the ticker belongs to.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ ticker, market }) => {
    const base = process.env.SUPABASE_URL;
    const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!base || !anon) {
      return { content: [{ type: "text", text: "Supabase env not configured" }], isError: true };
    }
    try {
      const r = await fetch(`${base}/functions/v1/get-stock-prices`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${anon}`,
          apikey: anon
        },
        body: JSON.stringify({ tickers: [ticker.toUpperCase()], market })
      });
      const text = await r.text();
      if (!r.ok) {
        return { content: [{ type: "text", text: `Upstream ${r.status}: ${text}` }], isError: true };
      }
      return {
        content: [{ type: "text", text }],
        structuredContent: { raw: safeJson(text) }
      };
    } catch (e) {
      return { content: [{ type: "text", text: `Fetch failed: ${e.message}` }], isError: true };
    }
  }
});
function safeJson(t) {
  try {
    return JSON.parse(t);
  } catch {
    return t;
  }
}

// src/lib/mcp/tools/search-stocks.ts
import { createClient } from "npm:@supabase/supabase-js@^2.52.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^4.4.3";
var search_stocks_default = defineTool2({
  name: "search_stocks",
  title: "Search stocks",
  description: "Search the public Market Canvas AI catalog of PSX (Pakistan Stock Exchange) or US stocks by ticker symbol or company name. Returns up to 20 matches.",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Text to match against ticker symbol or company name."),
    market: z2.enum(["PSX", "US"]).default("PSX").describe("Which market to search in.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, market }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Supabase env not configured" }], isError: true };
    }
    const supabase = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
    const table = market === "US" ? "us_stocks" : "Stocks";
    const { data, error } = await supabase.from(table).select("symbol, name, sector").or(`symbol.ilike.%${query}%,name.ilike.%${query}%`).order("symbol").limit(20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = (data ?? []).map((r) => ({ ticker: r.symbol, name: r.name, sector: r.sector }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { market, count: rows.length, results: rows }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "market-canvas-ai-mcp",
  title: "Market Canvas AI",
  version: "0.1.0",
  instructions: "Public tools for Market Canvas AI. Use `search_stocks` to find a PSX or US ticker by symbol or company name, and `get_stock_price` to fetch the latest price, absolute change, and percent change for a ticker. This server exposes only public market data \u2014 no user portfolios, watchlists, or alerts.",
  tools: [search_stocks_default, get_stock_price_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
