-- Create stocks table to store all Pakistani stock data
CREATE TABLE public.stocks (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  symbol TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  sector TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create indexes for better search performance
CREATE INDEX idx_stocks_symbol ON public.stocks(symbol);
CREATE INDEX idx_stocks_sector ON public.stocks(sector);
CREATE INDEX idx_stocks_name ON public.stocks(name);
CREATE INDEX idx_stocks_name_gin ON public.stocks USING gin(to_tsvector('english', name));

-- Enable Row Level Security
ALTER TABLE public.stocks ENABLE ROW LEVEL SECURITY;

-- Create policy to allow everyone to read stocks data (public data)
CREATE POLICY "Anyone can view stocks" 
ON public.stocks 
FOR SELECT 
USING (true);

-- Create function to update timestamps
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
NEW.updated_at = now();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for automatic timestamp updates
CREATE TRIGGER update_stocks_updated_at
BEFORE UPDATE ON public.stocks
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Insert all stock data
INSERT INTO public.stocks (symbol, name, sector) VALUES
('786', '786 Investments Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('AABS', 'Al-Abbas Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('AATM', 'Ali Asghar Textile Mills Limited', 'TEXTILE SPINNING'),
('ABL', 'Allied Bank Limited', 'COMMERCIAL BANKS'),
('ABOT', 'Abbott Laboratories (Pakistan) Limited', 'PHARMACEUTICALS'),
('ACIETF', 'Alfalah Consumer Index (ETF)', 'EXCHANGE TRADED FUNDS'),
('ACPL', 'Attock Cement Pakistan Limited', 'CEMENT'),
('ADAMS', 'Adam Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('ADMM', 'Artistic Denim Mills Limited', 'TEXTILE COMPOSITE'),
('AGHA', 'Agha Steel Ind.Ltd', 'ENGINEERING'),
('AGIC', 'Askari General Insurance Company Limited', 'INSURANCE'),
('AGIL', 'Agriauto Industries Limited', 'AUTOMOBILE PARTS & ACCESSORIES'),
('AGL', 'Agritech Limited', 'FERTILIZER'),
('AGLNCPS', 'Agritech Non-Voting (Pref) Class A', 'CHEMICAL'),
('AGP', 'AGP Limited', 'PHARMACEUTICALS'),
('AGSML', 'Abdullah Shah Ghazi Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('AGTL', 'Al-Ghazi Tractors Limited', 'AUTOMOBILE ASSEMBLER'),
('AHCL', 'Arif Habib Corporation Limited', 'FERTILIZER'),
('AHL', 'Arif Habib Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('AHTM', 'Ahmad Hassan Textile Mills Limited', 'TEXTILE COMPOSITE'),
('AICL', 'Adamjee Insurance Company Limited', 'INSURANCE'),
('AIRLINK', 'Air Link Communication Limited', 'TECHNOLOGY & COMMUNICATION'),
('AKBL', 'Askari Bank Limited', 'COMMERCIAL BANKS'),
('AKDHL', 'AKD Hospitality Limited', 'MISCELLANEOUS'),
('AKDSL', 'AKD Securities Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('AKGL', 'Al-Khair Gadoon Limited', 'MISCELLANEOUS'),
('ALAC', 'Askari Life Assurance Company Limited', 'INSURANCE'),
('ALIFE', 'Adamjee Life Assurance Company Limited', 'INSURANCE'),
('ALNRS', 'Al-Noor Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('ALTN', 'Altern Energy Limited', 'POWER GENERATION & DISTRIBUTION'),
('AMBL', 'Apna Microfinance Bank Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('ANL', 'Azgard Nine Limited', 'TEXTILE COMPOSITE'),
('ANLNV', 'Azgard Nine Non-Voting Ordinary Shares', 'TEXTILE COMPOSITE'),
('ANLPS', 'Azgard Nine 8.95%(Pref)', 'TEXTILE COMPOSITE'),
('ANTM', 'AN Textile Mills Limited', 'TEXTILE COMPOSITE'),
('APL', 'Attock Petroleum Limited', 'OIL & GAS MARKETING COMPANIES'),
('ARCTM', 'Arctic Textile Mills Limited', 'TEXTILE SPINNING'),
('ARPAK', 'Arpak International Investments Ltd.', 'MISCELLANEOUS'),
('ARPL', 'Archroma Pakistan Limited', 'CHEMICAL'),
('ASHT', 'Ashfaq Textile Mills Limited', 'TEXTILE WEAVING'),
('ASIC', 'Asia Insurance Company Limited', 'INSURANCE'),
('ASL', 'Aisha Steel Mills Limited', 'ENGINEERING'),
('ASLCPS', 'Aisha Steel Convt (Pref) Right', 'ENGINEERING'),
('ASLPS', 'Aisha Steel Convertible (Pref)', 'ENGINEERING'),
('ASTL', 'Amreli Steels Limited', 'ENGINEERING'),
('ATBA', 'Atlas Battery Limited', 'AUTOMOBILE PARTS & ACCESSORIES'),
('ATIL', 'Atlas Insurance Limited', 'INSURANCE'),
('ATLH', 'Atlas Honda Limited', 'AUTOMOBILE ASSEMBLER'),
('ATRL', 'Attock Refinery Limited', 'REFINERY'),
('AVN', 'Avanceon Limited', 'TECHNOLOGY & COMMUNICATION'),
('AWTX', 'Allawasaya Tex. & Finishing Mills Ltd', 'TEXTILE SPINNING'),
('BAFL', 'Bank Alfalah Limited', 'COMMERCIAL BANKS'),
('BAFS', 'Baba Farid Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('BAHL', 'Bank AL Habib Limited', 'COMMERCIAL BANKS'),
('BATA', 'Bata Pakistan Limited', 'LEATHER & TANNERIES'),
('BBFL', 'Big Bird Foods Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('BCL', 'Bolan Castings Limited', 'ENGINEERING'),
('BECO', 'Beco Steel Limited', 'ENGINEERING'),
('BERG', 'Berger Paints Pakistan Limited', 'CHEMICAL'),
('BFAGRO', 'Barkat Frisian Agro Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('BFBIO', 'BF Biosciences Limited', 'PHARMACEUTICALS'),
('BFMOD', 'B.F. Modaraba', 'MODARABAS'),
('BGL', 'Baluchistan Glass Limited', 'GLASS & CERAMICS'),
('BHAT', 'Bhanero Textile Mills Limited', 'TEXTILE COMPOSITE'),
('BIFO', 'Biafo Industries Limited', 'CHEMICAL'),
('BIPL', 'BankIslami Pakistan Limited', 'COMMERCIAL BANKS'),
('BML', 'Bank Makramah Limited', 'COMMERCIAL BANKS'),
('BNL', 'Bunnys Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('BNWM', 'Bannu Woollen Mills Limited', 'WOOLLEN'),
('BOK', 'The Bank of Khyber', 'COMMERCIAL BANKS'),
('BOP', 'The Bank of Punjab', 'COMMERCIAL BANKS'),
('BPL', 'Burshane LPG (Pakistan) Limited', 'OIL & GAS MARKETING COMPANIES'),
('BRRG', 'B.R.R Guardian Limited', 'PROPERTY'),
('BTL', 'Blessed Textiles Limited', 'TEXTILE COMPOSITE'),
('BUXL', 'Buxly Paints Limited', 'CHEMICAL'),
('BWCL', 'Bestway Cement Limited', 'CEMENT'),
('BWHL', 'Baluchistan Wheels Limited', 'AUTOMOBILE PARTS & ACCESSORIES'),
('CASH', 'Calcorp Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('CCM', 'Crescent Cotton Mills Limited', 'TEXTILE SPINNING'),
('CENI', 'Century Insurance Company Limited', 'INSURANCE'),
('CEPB', 'Century Paper & Board Mills Limited', 'PAPER, BOARD & PACKAGING'),
('CFL', 'Crescent Fibres Limited', 'TEXTILE SPINNING'),
('CHAS', 'Chashma Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('CHBL', 'Chenab Limited', 'TEXTILE COMPOSITE'),
('CHCC', 'Cherat Cement Company Limited', 'CEMENT'),
('CLCPS', 'Chenab Limited (Pref)', 'TEXTILE COMPOSITE'),
('CLOV', 'Clover Pakistan Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('CLVL', 'Cordoba Logistics & Ventures Limited', 'TRANSPORT'),
('CNERGY', 'Cnergyico PK Limited', 'REFINERY'),
('COLG', 'Colgate-Palmolive (Pakistan) Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('CPHL', 'Citi Pharma Ltd.', 'PHARMACEUTICALS'),
('CPPL', 'Cherat Packaging Limited', 'PAPER, BOARD & PACKAGING'),
('CRTM', 'The Crescent Textile Mills Limited', 'TEXTILE COMPOSITE'),
('CSAP', 'Crescent Steel & Allied Products Limited', 'ENGINEERING'),
('CSIL', 'Crescent Star Insurance Limited', 'INSURANCE'),
('CTM', 'Colony Textile Mills Limited', 'TEXTILE SPINNING'),
('CYAN', 'Cyan Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('DAAG', 'Data Agro Limited', 'CHEMICAL'),
('DADX', 'Dadex Eternit Limited', 'ENGINEERING'),
('DCL', 'Dewan Cement Limited', 'CEMENT'),
('DCR', 'Dolmen City REIT', 'REAL ESTATE INVESTMENT TRUST'),
('DEL', 'Dawood Equities Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('DFML', 'Dewan Farooque Motors Limited', 'AUTOMOBILE ASSEMBLER'),
('DFSM', 'Dewan Farooque Spinning Mills Limited', 'TEXTILE SPINNING'),
('DGKC', 'D.G. Khan Cement Company Limited', 'CEMENT'),
('DHPL', 'DH Partners Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('DIIL', 'Diamond Industries Limited', 'MISCELLANEOUS'),
('DINT', 'Din Textile Mills Limited', 'TEXTILE SPINNING'),
('DLL', 'Dawood Lawrencepur Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('DNCC', 'Dandot Cement Company Limited', 'CEMENT'),
('DOL', 'Descon Oxychem Limited', 'CHEMICAL'),
('DSIL', 'D.S. Industries Limited', 'TEXTILE SPINNING'),
('DYNO', 'Dynea Pakistan Limited', 'CHEMICAL'),
('ECOP', 'Ecopack Limited', 'MISCELLANEOUS'),
('EFERT', 'Engro Fertilizers Limited', 'FERTILIZER'),
('EFUG', 'EFU General Insurance Limited', 'INSURANCE'),
('EFUL', 'EFU Life Assurance Limited', 'INSURANCE'),
('ELCM', 'Elahi Cotton Mills Limited', 'TEXTILE SPINNING'),
('ELSM', 'Ellcot Spinning Mills Limited', 'TEXTILE SPINNING'),
('EMCO', 'Emco Industries Limited', 'CABLE & ELECTRICAL GOODS'),
('ENGROH', 'Engro Holdings Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('EPCL', 'Engro Polymer & Chemicals Limited', 'CHEMICAL'),
('EPCLPS', 'Engro Poly(Pref)', 'CHEMICAL'),
('EPQL', 'Engro Powergen Qadirpur Limited', 'POWER GENERATION & DISTRIBUTION'),
('ESBL', 'Escorts Investment Bank Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('EWIC', 'East West Insurance Company Limited', 'INSURANCE'),
('EXIDE', 'Exide Pakistan Limited', 'AUTOMOBILE PARTS & ACCESSORIES'),
('FABL', 'Faysal Bank Limited', 'COMMERCIAL BANKS'),
('FANM', 'First Al-Noor Modaraba', 'MODARABAS'),
('FASM', 'Faisal Spinning Mills Limited', 'TEXTILE COMPOSITE'),
('FATIMA', 'Fatima Fertilizer Company Limited', 'FERTILIZER'),
('FCCL', 'Fauji Cement Company Limited', 'CEMENT'),
('FCEPL', 'Frieslandcampina Engro Pakistan Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('FCIBL', 'First Credit and Investment Bank Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('FCL', 'Fast Cables Limited', 'CABLE & ELECTRICAL GOODS'),
('FCONM', 'First Constellation Modaraba', 'MODARABAS'),
('FCSC', 'First Capital Securities Corporation', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('FDPL', 'First Dawood Properties Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('FECM', 'First Elite Capital Modaraba', 'MODARABAS'),
('FECTC', 'Fecto Cement Limited', 'CEMENT'),
('FEM', 'First Equity Modaraba', 'MODARABAS'),
('FEROZ', 'Ferozsons Laboratories Limited', 'PHARMACEUTICALS'),
('FFC', 'Fauji Fertilizer Company Limited', 'FERTILIZER'),
('FFL', 'Fauji Foods Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('FFLM', 'First Fidelity Leasing Modaraba', 'MODARABAS'),
('FHAM', 'First Habib Modaraba', 'MODARABAS'),
('FIBLM', 'First IBL Modaraba', 'MODARABAS'),
('FIMM', 'First Imrooz Modaraba', 'MODARABAS'),
('FLYNG', 'Flying Cement Company Limited', 'CEMENT'),
('FML', 'Feroze1888 Mills Limited', 'TEXTILE COMPOSITE'),
('FNEL', 'First National Equities Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('FPJM', 'First Punjab Modaraba', 'MODARABAS'),
('FPRM', 'First Paramount Modaraba', 'MODARABAS'),
('FRCL', 'Frontier Ceramics Limited', 'GLASS & CERAMICS'),
('FRSM', 'Faran Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('FTMM', 'First Treet Manufacturing Modaraba', 'MODARABAS'),
('FTSM', 'First Tri-Star Modaraba', 'MODARABAS'),
('FZCM', 'Fazal Cloth Mills Limited', 'TEXTILE COMPOSITE'),
('GADT', 'Gadoon Textile Mills Limited', 'TEXTILE SPINNING'),
('GAL', 'Ghandhara Automobiles Limited', 'AUTOMOBILE ASSEMBLER'),
('GATI', 'Gatron (Industries) Limited', 'SYNTHETIC & RAYON'),
('GATM', 'Gul Ahmed Textile Mills Limited', 'TEXTILE COMPOSITE'),
('GCIL', 'Ghani Chemical Industries Limited', 'CHEMICAL'),
('GCWL', 'Ghani Chemworld Limited', 'CHEMICAL'),
('GFIL', 'Ghazi Fabrics International Limited', 'TEXTILE COMPOSITE'),
('GGGL', 'Ghani Global Glass Limited', 'GLASS & CERAMICS'),
('GGL', 'Ghani Global Holdings Limited', 'CHEMICAL'),
('GHGL', 'Ghani Glass Limited', 'GLASS & CERAMICS'),
('GHNI', 'Ghandhara Industries Limited', 'AUTOMOBILE ASSEMBLER'),
('GIL', 'Good Luck Industries Ltd.', 'FOOD & PERSONAL CARE PRODUCTS'),
('GLAXO', 'GlaxoSmithKline Pakistan Limited', 'PHARMACEUTICALS'),
('GLPL', 'Gillette Pakistan Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('GOC', 'GOC (Pak) Limited.', 'MISCELLANEOUS'),
('GRR', 'Globe Residency REIT', 'REAL ESTATE INVESTMENT TRUST'),
('GRYL', 'Grays Leasing Limited', 'LEASING COMPANIES'),
('GTYR', 'Ghandhara Tyre & Rubber Company Limited', 'AUTOMOBILE PARTS & ACCESSORIES'),
('GVGL', 'Ghani Value Glass Limited', 'GLASS & CERAMICS'),
('GWLC', 'Gharibwal Cement Limited', 'CEMENT'),
('HABSM', 'Habib Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('HAEL', 'Hala Enterprises Limited', 'TEXTILE COMPOSITE'),
('HAFL', 'Hafiz Limited', 'TEXTILE COMPOSITE'),
('HALEON', 'Haleon Pakistan Limited', 'PHARMACEUTICALS'),
('HBL', 'Habib Bank Limited', 'COMMERCIAL BANKS'),
('HBLTETF', 'HBL Total Treasury (ETF)', 'EXCHANGE TRADED FUNDS'),
('HCAR', 'Honda Atlas Cars (Pakistan) Limited', 'AUTOMOBILE ASSEMBLER'),
('HGFA', 'HBL Growth Fund', 'CLOSE - END MUTUAL FUND'),
('HICL', 'Habib Insurance Company Limited', 'INSURANCE'),
('HIFA', 'HBL Investment Fund', 'CLOSE - END MUTUAL FUND'),
('HINO', 'Hinopak Motors Limited', 'AUTOMOBILE ASSEMBLER'),
('HINOON', 'Highnoon Laboratories Limited', 'PHARMACEUTICALS'),
('HMB', 'Habib Metropolitan Bank Limited', 'COMMERCIAL BANKS'),
('HPL', 'Hoechst Pakistan Limited', 'PHARMACEUTICALS'),
('HRPL', 'Habib Rice Product Limited.', 'SUGAR & ALLIED INDUSTRIES'),
('HTL', 'Hi-Tech Lubricants Limited', 'OIL & GAS MARKETING COMPANIES'),
('HUBC', 'The Hub Power Company Limited', 'POWER GENERATION & DISTRIBUTION'),
('HUMNL', 'Hum Network Limited', 'TECHNOLOGY & COMMUNICATION'),
('HUSI', 'Husein Industries Limited', 'PROPERTY'),
('IBFL', 'Ibrahim Fibres Limited', 'SYNTHETIC & RAYON'),
('IBLHL', 'IBL HealthCare Limited', 'PHARMACEUTICALS'),
('ICCI', 'ICC Industries Limited', 'TEXTILE WEAVING'),
('ICIBL', 'Invest Capital Investment Bank Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('ICL', 'Ittehad Chemicals Limted', 'CHEMICAL'),
('IDRT', 'Idrees Textile Mills Limited', 'TEXTILE SPINNING'),
('IDSM', 'Ideal Spinning Mills Limited', 'TEXTILE SPINNING'),
('IDYM', 'Indus Dyeing & Manufacturing Co. Limited', 'TEXTILE SPINNING'),
('IGIHL', 'IGI Holdings Limited', 'INSURANCE'),
('IGIL', 'IGI Life Insurance Limited', 'INSURANCE'),
('ILP', 'Interloop Limited', 'TEXTILE COMPOSITE'),
('IMAGE', 'Image Pakistan Limited', 'SYNTHETIC & RAYON'),
('IML', 'Imperial Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('IMS', 'Intermarket Securities Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('INDU', 'Indus Motor Company Limited', 'AUTOMOBILE ASSEMBLER'),
('INIL', 'International Industries Limited', 'ENGINEERING'),
('INKL', 'International Knitwear Limited', 'TEXTILE COMPOSITE'),
('IPAK', 'International Packaging Films Limited', 'PAPER, BOARD & PACKAGING'),
('ISIL', 'Ismail Industries Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('ISL', 'International Steels Limited', 'ENGINEERING'),
('ITTEFAQ', 'Ittefaq Iron Industries Limited', 'ENGINEERING'),
('JDMT', 'Janana De Malucho Textile Mills Limited', 'TEXTILE SPINNING'),
('JDWS', 'JDW Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('JGICL', 'Jubilee General Insurance Limited', 'INSURANCE'),
('JKSM', 'J.K. Spinning Mills Limited', 'TEXTILE SPINNING'),
('JLICL', 'Jubilee Life Insurance Company Limited', 'INSURANCE'),
('JSBL', 'JS Bank Limited', 'COMMERCIAL BANKS'),
('JSCL', 'Jahangir Siddiqui & Co. Ltd.', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('JSCLPSA', 'Jahangir Sidd(Pref)', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('JSGBETF', 'JS Global Banking Sector(ETF)', 'EXCHANGE TRADED FUNDS'),
('JSGCL', 'JS Global Capital Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('JSIL', 'JS Investments Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('JSMFETF', 'JS Momentum Factor Exchange Traded Fund', 'EXCHANGE TRADED FUNDS'),
('JSML', 'Jauharabad Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('JVDC', 'Javedan Corporation Limited', 'PROPERTY'),
('JVDCPS', 'Javedan Corporation (Pref)', 'PROPERTY'),
('KAPCO', 'Kot Addu Power Company Limited', 'POWER GENERATION & DISTRIBUTION'),
('KCL', 'Karam Ceramics Limited', 'GLASS & CERAMICS'),
('KEL', 'K-Electric Limited', 'POWER GENERATION & DISTRIBUTION'),
('KHTC', 'Khyber Tobacco Company Limited', 'TOBACCO'),
('KHYT', 'Khyber Textile Mills Limited', 'TEXTILE COMPOSITE'),
('KML', 'Kohinoor Mills Limited', 'TEXTILE COMPOSITE'),
('KOHC', 'Kohat Cement Company Limited', 'CEMENT'),
('KOHE', 'Kohinoor Energy Limited', 'POWER GENERATION & DISTRIBUTION'),
('KOHP', 'Kohinoor Power Company Limited', 'POWER GENERATION & DISTRIBUTION'),
('KOHTM', 'Kohat Textile Mills Limited', 'TEXTILE SPINNING'),
('KOIL', 'Kohinoor Industries Limited', 'TEXTILE COMPOSITE'),
('KOSM', 'Kohinoor Spinning Mills Limited', 'TEXTILE SPINNING'),
('KPUS', 'Khairpur Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('KSBP', 'KSB Pumps Company Limited', 'ENGINEERING'),
('KTML', 'Kohinoor Textile Mills Limited', 'TEXTILE COMPOSITE'),
('LCI', 'Lucky Core Industries Limited', 'CHEMICAL'),
('LEUL', 'Leather Up Limited', 'LEATHER & TANNERIES'),
('LIVEN', 'Liven Pharma Limited', 'PHARMACEUTICALS'),
('LOADS', 'Loads Limited', 'AUTOMOBILE PARTS & ACCESSORIES'),
('LOTCHEM', 'Lotte Chemical Pakistan Limited', 'CHEMICAL'),
('LPGL', 'Leiner Pak Gelatine Limited', 'CHEMICAL'),
('LPL', 'Lalpir Power Limited', 'POWER GENERATION & DISTRIBUTION'),
('LSECL', 'LSE Capital Limited.', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('LSEFSL', 'LSE Financial Services Limited.', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('LSEVL', 'LSE Ventures Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('LUCK', 'Lucky Cement Limited', 'CEMENT'),
('MACFL', 'MACPAC Films Limited', 'PAPER, BOARD & PACKAGING'),
('MACTER', 'Macter International Limited', 'PHARMACEUTICALS'),
('MARI', 'Mari Energies Limited', 'OIL & GAS EXPLORATION COMPANIES'),
('MCB', 'MCB Bank Limited', 'COMMERCIAL BANKS'),
('MCBIM', 'MCB Investment Management Limited.', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('MDTL', 'Media Times Limited', 'TECHNOLOGY & COMMUNICATION'),
('MEBL', 'Meezan Bank Limited', 'COMMERCIAL BANKS'),
('MEHT', 'Mehmood Textile Mills Limited', 'TEXTILE COMPOSITE'),
('MERIT', 'Merit Packaging Limited', 'PAPER, BOARD & PACKAGING'),
('MFFL', 'Mitchells Fruit Farms Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('MFL', 'Matco Foods Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('MIIETF', 'Mahaana Islamic Index ETF', 'EXCHANGE TRADED FUNDS'),
('MIRKS', 'Mirpurkhas Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('MLCF', 'Maple Leaf Cement Factory Limited', 'CEMENT'),
('MQTM', 'Maqbool Textile Mills Limited', 'TEXTILE SPINNING'),
('MRNS', 'Mehran Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('MSCL', 'Metropolitan Steel Corporation Limited', 'ENGINEERING'),
('MSOT', 'Masood Textile Mills Limited', 'TEXTILE COMPOSITE'),
('MSOTPS', 'Masood Textile (Pref)', 'TEXTILE COMPOSITE'),
('MTL', 'Millat Tractors Limited', 'AUTOMOBILE ASSEMBLER'),
('MUGHAL', 'Mughal Iron & Steel Industries Limited', 'ENGINEERING'),
('MUGHALC', 'Mughal Iron & Steel Industries Ltd(C)', 'ENGINEERING'),
('MUREB', 'Murree Brewery Company Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('MWMP', 'Mandviwala Mauser Plastic Industries', 'MISCELLANEOUS'),
('MZNPETF', 'Meezan Pakistan ETF', 'EXCHANGE TRADED FUNDS'),
('NAGC', 'Nagina Cotton Mills Limited', 'TEXTILE SPINNING'),
('NATF', 'National Foods Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('NATM', 'Nadeem Textile Mills Limited', 'TEXTILE SPINNING'),
('NBP', 'National Bank of Pakistan', 'COMMERCIAL BANKS'),
('NBPGETF', 'NBP Pakistan Growth ETF', 'EXCHANGE TRADED FUNDS'),
('NCL', 'Nishat Chunian Limited', 'TEXTILE COMPOSITE'),
('NCPL', 'Nishat Chunian Power Limited', 'POWER GENERATION & DISTRIBUTION'),
('NESTLE', 'Nestle Pakistan Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('NETSOL', 'NetSol Technologies Limited', 'TECHNOLOGY & COMMUNICATION'),
('NEXT', 'Next Capital Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('NICL', 'Nimir Industrial Chemicals Limited', 'CHEMICAL'),
('NITGETF', 'NIT Pakistan Gateway ETF', 'EXCHANGE TRADED FUNDS'),
('NML', 'Nishat Mills Limited', 'TEXTILE COMPOSITE'),
('NONS', 'Noon Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('NPL', 'Nishat Power Limited', 'POWER GENERATION & DISTRIBUTION'),
('NRL', 'National Refinery Limited', 'REFINERY'),
('NRSL', 'Nimir Resins Limited', 'CHEMICAL'),
('NSRM', 'The National Silk & Rayon Mills Limited', 'SYNTHETIC & RAYON'),
('OBOY', 'Oilboy Energy Limited', 'OIL & GAS MARKETING COMPANIES'),
('OCTOPUS', 'Octopus Digital Limited', 'TECHNOLOGY & COMMUNICATION'),
('OGDC', 'Oil & Gas Development Company Limited', 'OIL & GAS EXPLORATION COMPANIES'),
('OLPL', 'OLP Financial Services Pakistan Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('OLPM', 'OLP Modaraba', 'MODARABAS'),
('OML', 'Olympia Mills Limited', 'MISCELLANEOUS'),
('ORM', 'Orient Rental Mod', 'MODARABAS'),
('OTSU', 'Otsuka Pakistan Limited', 'PHARMACEUTICALS'),
('PABC', 'Pakistan Aluminium Beverage Cans Limited', 'MISCELLANEOUS'),
('PACE', 'Pace (Pakistan) Limited', 'PROPERTY'),
('PAEL', 'Pak Elektron Limited', 'CABLE & ELECTRICAL GOODS'),
('PAKD', 'Pak Datacom Limited', 'TECHNOLOGY & COMMUNICATION'),
('PAKL', 'Pak Leather Crafts Limited', 'LEATHER & TANNERIES'),
('PAKOXY', 'Pakistan Oxygen Limited', 'CHEMICAL'),
('PAKRI', 'Pakistan Reinsurance Company Limited', 'INSURANCE'),
('PAKT', 'Pakistan Tobacco Company Limited', 'TOBACCO'),
('PCAL', 'Pakistan Cables Limited', 'CABLE & ELECTRICAL GOODS'),
('PGLC', 'Pak-Gulf Leasing Company Limited', 'LEASING COMPANIES'),
('PIAHCLA', 'PIA Holding Company Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('PIAHCLB', 'PIA Holding Company LimitedB', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('PIBTL', 'Pakistan International Bulk Terminal', 'TRANSPORT'),
('PICT', 'Pakistan International Container', 'TRANSPORT'),
('PIM', 'Popular Islamic Modaraba', 'MODARABAS'),
('PINL', 'Premier Insurance Limited', 'INSURANCE'),
('PIOC', 'Pioneer Cement Limited', 'CEMENT'),
('PKGI', 'The Pakistan General Insurance Co. Ltd.', 'INSURANCE'),
('PKGP', 'Pakgen Power Limited', 'POWER GENERATION & DISTRIBUTION'),
('PKGS', 'Packages Limited', 'PAPER, BOARD & PACKAGING'),
('PMI', 'First Prudential Modaraba', 'MODARABAS'),
('PMPK', 'Philip Morris (Pakistan) Limited', 'TOBACCO'),
('PMRS', 'The Premier Sugar Mills', 'SUGAR & ALLIED INDUSTRIES'),
('PNSC', 'Pakistan National Shipping Corporation', 'TRANSPORT'),
('POL', 'Pakistan Oilfields Limited', 'OIL & GAS EXPLORATION COMPANIES'),
('POML', 'Punjab Oil Mills Limited', 'VANASPATI & ALLIED INDUSTRIES'),
('POWER', 'Power Cement Limited', 'CEMENT'),
('POWERPS', 'Power Cement (Pref)', 'CEMENT'),
('PPL', 'Pakistan Petroleum Limited', 'OIL & GAS EXPLORATION COMPANIES'),
('PPP', 'Pakistan Paper Products Limited', 'PAPER, BOARD & PACKAGING'),
('PREMA', 'At-Tahur Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('PRET', 'Premium Textile Mills Limited', 'TEXTILE SPINNING'),
('PRL', 'Pakistan Refinery Limited', 'REFINERY'),
('PRWM', 'Prosperity Weaving Mills Limited', 'TEXTILE WEAVING'),
('PSEL', 'Pakistan Services Limited', 'MISCELLANEOUS'),
('PSO', 'Pakistan State Oil Company Limited', 'OIL & GAS MARKETING COMPANIES'),
('PSX', 'Pakistan Stock Exchange Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('PSYL', 'Pakistan Synthetics Limited', 'SYNTHETIC & RAYON'),
('PTC', 'Pakistan Telecommunication Company Ltd', 'TECHNOLOGY & COMMUNICATION'),
('PTL', 'Panther Tyres Ltd.', 'AUTOMOBILE PARTS & ACCESSORIES'),
('QUICE', 'Quice Food Industries Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('RCML', 'Reliance Cotton Spinning Mills Limited', 'TEXTILE SPINNING'),
('REDCO', 'Redco Textiles Limited', 'TEXTILE COMPOSITE'),
('REWM', 'Reliance Weaving Mills Limited', 'TEXTILE COMPOSITE'),
('RICL', 'Reliance Insurance Company Limited', 'INSURANCE'),
('RMPL', 'Rafhan Maize Products Company Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('RPL', 'Roshan Packages Limited', 'PAPER, BOARD & PACKAGING'),
('RUPL', 'Rupali Polyester Limited', 'SYNTHETIC & RAYON'),
('SAIF', 'Saif Textile Mills Limited', 'TEXTILE SPINNING'),
('SANSM', 'Sanghar Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('SAPT', 'Sapphire Textile Mills Limited', 'TEXTILE COMPOSITE'),
('SARC', 'Sardar Chemical Industries Limited', 'CHEMICAL'),
('SASML', 'Sindh Abadgars Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('SAZEW', 'Sazgar Engineering Works Limited', 'AUTOMOBILE ASSEMBLER'),
('SBL', 'Samba Bank Limited', 'COMMERCIAL BANKS'),
('SCBPL', 'Standard Chartered Bank (Pak) Ltd', 'COMMERCIAL BANKS'),
('SCL', 'Shield Corporation Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('SEARL', 'The Searle Company Limited', 'PHARMACEUTICALS'),
('SEL', 'Sitara Energy Limited', 'POWER GENERATION & DISTRIBUTION'),
('SEPL', 'Security Papers Limited', 'PAPER, BOARD & PACKAGING'),
('SERT', 'Service Industries Textiles Limited', 'TEXTILE SPINNING'),
('SFL', 'Sapphire Fibres Limited', 'TEXTILE COMPOSITE'),
('SGF', 'Service GlobalFootwear Limited', 'LEATHER & TANNERIES'),
('SGPL', 'S.G. Power Limited', 'POWER GENERATION & DISTRIBUTION'),
('SHCM', 'Shadman Cotton Mills Limited', 'TEXTILE SPINNING'),
('SHDT', 'Shadab Textile Mills Limited', 'TEXTILE SPINNING'),
('SHEZ', 'Shezan International Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('SHFA', 'Shifa International Hospitals Limited', 'MISCELLANEOUS'),
('SHJS', 'Shahtaj Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('SHNI', 'Shaheen Insurance Company Limited', 'INSURANCE'),
('SHSML', 'Shahmurad Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('SIBL', 'Security Investment Bank Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('SIEM', 'Siemens (Pakistan) Engineering', 'CABLE & ELECTRICAL GOODS'),
('SINDM', 'Sindh Modaraba', 'MODARABAS'),
('SITC', 'Sitara Chemical Industries Limited', 'CHEMICAL'),
('SLCPA', 'Security Leasing Corp.9.10%(Pref)', 'LEASING COMPANIES'),
('SLGL', 'Secure Logistics Group Limited', 'TRANSPORT'),
('SMCPL', 'Safe Mix Concrete Limited', 'CEMENT'),
('SNAI', 'Sana Industries Limited', 'TEXTILE SPINNING'),
('SNBL', 'Soneri Bank Limited', 'COMMERCIAL BANKS'),
('SNGP', 'Sui Northern Gas Pipelines Limited', 'OIL & GAS MARKETING COMPANIES'),
('SPEL', 'SPEL Limited', 'PAPER, BOARD & PACKAGING'),
('SPWL', 'Saif Power Limited', 'POWER GENERATION & DISTRIBUTION'),
('SRVI', 'Service Industries Limited', 'LEATHER & TANNERIES'),
('SSGC', 'Sui Southern Gas Company Limited', 'OIL & GAS MARKETING COMPANIES'),
('SSOM', 'S.S.Oil Mills Limited', 'VANASPATI & ALLIED INDUSTRIES'),
('STCL', 'Shabbir Tiles & Ceramics Limited', 'GLASS & CERAMICS'),
('STJT', 'Shahtaj Textile Limited', 'TEXTILE WEAVING'),
('STL', 'Supernet Technologies Limited', 'TECHNOLOGY & COMMUNICATION'),
('STML', 'Shams Textile Mills Limited', 'TEXTILE COMPOSITE'),
('STYLERS', 'Stylers International Limited', 'TEXTILE COMPOSITE'),
('SURC', 'Suraj Cotton Mills Limited', 'TEXTILE COMPOSITE'),
('SUTM', 'Sunrays Textile Mills Limited', 'TEXTILE SPINNING'),
('SYM', 'Symmetry Group Limited', 'TECHNOLOGY & COMMUNICATION'),
('SYS', 'Systems Limited', 'TECHNOLOGY & COMMUNICATION'),
('SZTM', 'Shahzad Textile Mills Limited', 'TEXTILE SPINNING'),
('TATM', 'Tata Textile Mills Limited', 'TEXTILE SPINNING'),
('TBL', 'Treet Battery Limited.', 'AUTOMOBILE PARTS & ACCESSORIES'),
('TCORP', 'Tariq Corporation Limited', 'SUGAR & ALLIED INDUSTRIES'),
('TCORPCPS', 'Tariq Corporation Limited(Pref)', 'SUGAR & ALLIED INDUSTRIES'),
('TELE', 'Telecard Limited', 'TECHNOLOGY & COMMUNICATION'),
('TGL', 'Tariq Glass Industries Limited', 'GLASS & CERAMICS'),
('THALL', 'Thal Limited', 'AUTOMOBILE PARTS & ACCESSORIES'),
('THCCL', 'Thatta Cement Company Limited', 'CEMENT'),
('TICL', 'The Thal Industries Corporation Limited', 'SUGAR & ALLIED INDUSTRIES'),
('TOMCL', 'The Organic Meat Company Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('TOWL', 'Towellers Limited', 'TEXTILE COMPOSITE'),
('TPL', 'TPL Corp Limited', 'TECHNOLOGY & COMMUNICATION'),
('TPLI', 'TPL Insurance Limited', 'INSURANCE'),
('TPLL', 'TPL Life Insurance Limited', 'INSURANCE'),
('TPLP', 'TPL Properties Limited', 'PROPERTY'),
('TPLRF1', 'TPL REIT Fund I', 'REAL ESTATE INVESTMENT TRUST'),
('TPLT', 'TPL Trakker Limited', 'TECHNOLOGY & COMMUNICATION'),
('TREET', 'Treet Corporation Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('TRG', 'TRG Pakistan Limited', 'TECHNOLOGY & COMMUNICATION'),
('TRIPF', 'Tri-Pack Films Limited', 'MISCELLANEOUS'),
('TRSM', 'Trust Modaraba', 'MODARABAS'),
('TSBL', 'Trust Securities & Brokerage Limited', 'INV. BANKS / INV. COS. / SECURITIES COS.'),
('TSMF', 'Tri-Star Mutual Fund Limited', 'CLOSE - END MUTUAL FUND'),
('TSML', 'Tandlianwala Sugar Mills Limited', 'SUGAR & ALLIED INDUSTRIES'),
('TSPL', 'Tri-Star Power Limited', 'POWER GENERATION & DISTRIBUTION'),
('UBDL', 'United Brands Limited', 'MISCELLANEOUS'),
('UBL', 'United Bank Limited', 'COMMERCIAL BANKS'),
('UBLPETF', 'UBLPakistan Enterprise ETF', 'EXCHANGE TRADED FUNDS'),
('UCAPM', 'Unicap Modaraba', 'MODARABAS'),
('UDLI', 'UDL International Limited', 'MISCELLANEOUS'),
('UDPL', 'United Distributors Pakistan Limited', 'MISCELLANEOUS'),
('UNIC', 'The United Insurance Company', 'INSURANCE'),
('UNITY', 'Unity Foods Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('UPFL', 'Unilever Pakistan Foods Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('UVIC', 'The Universal Insurance Company Limited', 'INSURANCE'),
('WAFI', 'Wafi Energy Pakistan Limited', 'OIL & GAS MARKETING COMPANIES'),
('WAHN', 'Wah Noble Chemicals Limited', 'CHEMICAL'),
('WAVES', 'Waves Corporation Limited', 'CABLE & ELECTRICAL GOODS'),
('WAVESAPP', 'Waves Home Appliances Limited', 'CABLE & ELECTRICAL GOODS'),
('WTL', 'Worldcall Telecom Limited', 'TECHNOLOGY & COMMUNICATION'),
('YOUW', 'Yousaf Weaving Mills Limited', 'TEXTILE WEAVING'),
('ZAHID', 'Zahidjee Textile Mills Limited', 'TEXTILE COMPOSITE'),
('ZAL', 'Zarea Limited', 'TECHNOLOGY & COMMUNICATION'),
('ZIL', 'ZIL Limited', 'FOOD & PERSONAL CARE PRODUCTS'),
('ZTL', 'Zephyr Textiles Limited', 'TEXTILE WEAVING'),
-- Add KSE100 as a special index
('KSE100', 'KSE-100 Index', 'MISCELLANEOUS'),
-- Add some additional popular stocks that were in the old list
('ENGRO', 'Engro Corporation Limited', 'FERTILIZER'),
('DAWH', 'D.A.W.H. Textile Mills Limited', 'TEXTILE COMPOSITE');