// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnhnhiaeobjyyulgmxho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuaG5oaWFlb2JqeXl1bGdteGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjA3OTQsImV4cCI6MjA2ODU5Njc5NH0.oXM1WoTO8zmy8l8N4M44-z3HIluzBNX6jub0s7dt9XQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});